### ISSUE TITLE
RuntimeError: Expected object of scalar type long int but got scalar type float for sequence element 55970.

### ISSUE THREAD

**Issue by ccandee** [rusty1s/himp-gnn#1]
Hi,

Thanks for the awesome work! When I ran `python train_ogbpcba.py`

I got the following error:

> Namespace(device=0, dropout=0.25, epochs=150, hidden_channels=300, no_inter_message_passing=False, num_layers=3)
> Downloading https://snap.stanford.edu/ogb/data/graphproppred/csv_mol_download/pcba.zip
> Downloaded 0.04 GB: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [00:02<00:00, 14.08it/s]
> Extracting data/pcba.zip
> Processing...
> Loading necessary files...
> This might take a while.
> Processing graphs...
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 437929/437929 [00:02<00:00, 148731.74it/s]
> Converting graphs into PyG objects...
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 437929/437929 [00:02<00:00, 148342.39it/s]
> Traceback (most recent call last):
>   File "train_ogbpcba.py", line 36, in <module>
>     dataset = PygGraphPropPredDataset(name, 'data', pre_transform=transform)
>   File "/home/muhan/anaconda3/envs/seal/lib/python3.8/site-packages/ogb/graphproppred/dataset_pyg.py", line 43, in __init__
>     super(PygGraphPropPredDataset, self).__init__(self.root, transform, pre_transform)
>   File "/home/muhan/anaconda3/envs/seal/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
>     super(InMemoryDataset, self).__init__(root, transform, pre_transform,
>   File "/home/muhan/anaconda3/envs/seal/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
>     self._process()
>   File "/home/muhan/anaconda3/envs/seal/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 166, in _process
>     self.process()
>   File "/home/muhan/anaconda3/envs/seal/lib/python3.8/site-packages/ogb/graphproppred/dataset_pyg.py", line 130, in process
>     data, slices = self.collate(data_list)
>   File "/home/muhan/anaconda3/envs/seal/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 115, in collate
>     data[key] = torch.cat(data[key],
> RuntimeError: Expected object of scalar type long int but got scalar type float for sequence element 55970.

Could you have a look? I am using torch-geometric 1.5.0, pytorch 1.5.1 and ogb 1.2.1.

**Comment by rusty1s** [comment]
Sorry for the inconveniences! This should be fixed in `torch-geometric==master`. Can you check it?

**Comment by ccandee** [comment]
Thanks for the fix! This time the preprocessing works. However, it returns the error:

> Run 1:
> 
> Traceback (most recent call last):
>   File "train_ogbpcba.py", line 98, in <module>
>     loss = train(epoch)
>   File "train_ogbpcba.py", line 58, in train
>     for data in train_loader:
>   File "/home/muhan/anaconda3/envs/pygdev/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
>     data = self._next_data()
>   File "/home/muhan/anaconda3/envs/pygdev/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
>     idx, data = self._get_data()
>   File "/home/muhan/anaconda3/envs/pygdev/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
>     success, data = self._try_get_data()
>   File "/home/muhan/anaconda3/envs/pygdev/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
>     data = self._data_queue.get(timeout=timeout)
>   File "/home/muhan/anaconda3/envs/pygdev/lib/python3.8/multiprocessing/queues.py", line 116, in get
>     return _ForkingPickler.loads(res)
>   File "/home/muhan/anaconda3/envs/pygdev/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
>     fd = df.detach()
>   File "/home/muhan/anaconda3/envs/pygdev/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
>     return reduction.recv_handle(conn)
>   File "/home/muhan/anaconda3/envs/pygdev/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
>     return recvfds(s, 1)[0]
>   File "/home/muhan/anaconda3/envs/pygdev/lib/python3.8/multiprocessing/reduction.py", line 164, in recvfds
>     raise RuntimeError('received %d items of ancdata' %
> RuntimeError: received 0 items of ancdata

I guess it has something to do with my new environment, because the training works after I copy the preprocessed data to my previous environment.
