### ISSUE TITLE
Not really an issue, but a question about your GINEConv

### ISSUE THREAD

**Issue by rhjohnstone** [rusty1s/himp-gnn#10]
https://github.com/rusty1s/himp-gnn/blob/0a506bb6ecc66b5ffc29b9b229c28a805adb06c1/model.py#L138-L141

Is there a reason why your last three lines haven't just been added to your `nn` in `self.atom_convs[i]`? It seems like it's basically continuing a sequence that we could have wrapped up in the original `nn`. Please let me know if I'm missing something.

**Comment by rusty1s** [comment]
Yeah, one can do easily do this. It does not change the model at all.
