### ISSUE TITLE
multitask issue

### ISSUE THREAD

**Issue by thegodone** [rusty1s/himp-gnn#5]
Using PyG 1.5.0 or 1.6.1

got this error during python run:

Traceback (most recent call last):
  File "train_tox21.py", line 113, in <module>
    if val_perf > best_val_perf:
TypeError: '>' not supported between instances of 'dict' and 'int'

same for Hiv:

Traceback (most recent call last):
  File "train_hiv.py", line 113, in <module>
    if val_perf > best_val_perf:
TypeError: '>' not supported between instances of 'dict' and 'int'

**Comment by thegodone** [comment]
Fix using this code:
        if val_perf["rocauc"] > best_val_perf:
            best_val_perf = val_perf["rocauc"]
            test_perf = test(test_loader)

        print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}, '
              f'Train: {train_perf["rocauc"]:.4f}, Val: {val_perf["rocauc"]:.4f}, '
              f'Test: {test_perf["rocauc"]:.4f}')

    test_perfs.append(test_perf["rocauc"])

**Comment by rusty1s** [comment]
Thanks, that's indeed a bug. Fixed it.
