### ISSUE TITLE
train_muv.py has a TypeError

### ISSUE THREAD

**Issue by toushi68** [rusty1s/himp-gnn#8]
Hi,
Here is the output:
Traceback (most recent call last):
  File "train_muv.py", line 113, in <module>
    if val_perf > best_val_perf:
TypeError: '>' not supported between instances of 'dict' and 'int'

and the bug looks like from this line:
https://github.com/rusty1s/himp-gnn/blob/5f8573b1a6f579ae95c918bbd2a44dacf0db2e37/train_muv.py#L95

**Comment by rusty1s** [comment]
Thanks for reporting, should be fixed in master.
